### ISSUE TITLE
Recoil gamez.zbd doesn't extract - unexpected version

### ISSUE THREAD

**Issue by Kazade** [TerranMechworks/mech3ax#1]
I'm not sure if I'm doing something wrong, but this is what I get:

```
$ unzbd gamez gamez.zbd gamez.zip
Error: Failed to read gamez data

Caused by:
    Expected 'version' == 27, but was 15 (at 4)
```

It's the same for all "m" folders.

**Comment by tobywf** [comment]
Presumably "m" folders are Recoil and you are using version 0.5.0? Try the latest [release candidate](https://github.com/TerranMechworks/mech3ax/releases/tag/v0.6.0-rc4), bearing in mind the [supported files](https://github.com/TerranMechworks/mech3ax/tree/v0.6.0-rc4#support-matrix). v0.5.0 doesn't support Recoil. See the changelog for details.

There is also a Recoil discord, I can shoot you an invite per email if you'd like to join.

**Comment by Kazade** [comment]
You mean, there's more than just me who still loves this game?!
